### ISSUE TITLE
potential minor bug?

### ISSUE THREAD

**Issue by min-xu-ai** [scottchiefbaker/dool#26] opened 2022-06-27 20:28 UTC
see this

##### SUMMARY
I occationally see this.

```
  File "/usr/lib/python-exec/python3.9/dstat", line 2830, in <module>
    main()
  File "/usr/lib/python-exec/python3.9/dstat", line 2689, in main
    scheduler.run()
  File "/usr/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/usr/lib/python-exec/python3.9/dstat", line 2787, in perform
    line = line + o.show() + o.showend(totlist, vislist)
  File "/usr/lib/python-exec/python3.9/dstat", line 521, in show
    line = line + cprintlist(self.val[name], ctype, self.width, scale)
  File "/usr/lib/python-exec/python3.9/dstat", line 2089, in cprintlist
    ret = ret + sep + cprint(var, ctype, width, scale)
  File "/usr/lib/python-exec/python3.9/dstat", line 2139, in cprint
    ret, c = dchg(var, width, base)
  File "/usr/lib/python-exec/python3.9/dstat", line 2039, in dchg
    ret = str(int(round(var)))
OverflowError: cannot convert float infinity to integer
```

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### DSTAT VERSION
```
<!--- Paste verbatim output from “dstat --version” here between tripple quotes -->
```

##### STEPS TO REPRODUCE

```
<!--- Paste example use or output here between quotes -->
```

##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by Korkman** [comment] 2023-02-22 17:54
Duplicate of #3

**Comment by scottchiefbaker** [comment] 2023-06-03 03:04
Dupe of #3

**Closed by scottchiefbaker** 2023-06-03 03:04 UTC
