### ISSUE TITLE
Optional ANSI 16-color theme

### ISSUE THREAD

**Issue by leahneukirchen** [scottchiefbaker/dool#18] opened 2022-01-22 00:12 UTC
##### SUMMARY

dool now uses 256-colors which doesn't fit into my terminal emulator color scheme.

##### ISSUE TYPE

 - Feature Idea

Would you accept a patch that re-enables the old 16-color scheme as an option?

**Comment by malventano** [comment] 2023-02-05 12:31
The ANSI changes of 1.1.0 break the bottom line colors even in 256 color terminals (dstat for reference):
![image](https://user-images.githubusercontent.com/29584411/216818683-2cb583bc-7402-48d8-91bf-9af983e29702.png)
Along with the ability to re-enable the old scheme, dool should probably check the $TERM type and revert as necessary.

**Comment by scottchiefbaker** [comment] 2023-06-03 03:03
Yes... if you wrote a patch for a 16 color terminal I would accept it.

How does the 256 color scheme NOT fit in to your terminal emulator?

**Comment by leahneukirchen** [comment] 2023-06-03 13:00
I probably didn't make myself very clear: A terminal color theme defines the colors for the 16 base colors. The 256 colors are the same for every terminal. So if I want dool to use *my* terminal color scheme, it should only use the base 16 colors.

**Comment by leahneukirchen** [comment] 2023-06-03 13:02
I have a patch for this, will PR.

**Comment by scottchiefbaker** [comment] 2023-06-05 17:49
@malventano can you open a separate issue for the bottom line colors? I'm not able to reproduce.

**Comment by scottchiefbaker** [comment] 2023-06-07 16:46
@malventano I just landed 5371f754 which might address your color concerns.

**Comment by scottchiefbaker** [comment] 2023-07-05 17:26
This has been added as the `--color16` option

**Closed by scottchiefbaker** 2023-07-05 17:26 UTC
